Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,9 +13,9 @@ build:
         - npm run build
     artifacts:
         paths:
-            - "/build"
-            - "/prisma"
-            - "/node_modules"
+            - "build/"
+            - "prisma/"
+            - "node_modules/"
         expire_in: 1h
 
 test:
@@ -30,6 +30,14 @@ test:
         DATABASE_URL: postgres://prisma:prisma@db:5432/appdb
     dependencies:
         - build
+    before_script:
+        - |
+            for path in build prisma node_modules; do
+                if [ ! -e "$path" ]; then
+                echo "‼️ Required artifact '$path' not found. Aborting."
+                exit 1
+                fi
+            done
     script:
         - npm run start &
         - npx wait-on tcp:db:5432 tcp:localhost:3000
